
# npm run build
FROM --platform=linux/amd64 node:alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

#  Deploying to nginx

FROM --platform=linux/amd64 nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf



# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]